using System;
using System.IO;
using System.Text;
using System.Threading;
using EmbyThemeMaker.Config;
using EmbyThemeMaker.Theme;
using Xunit;

namespace EmbyThemeMaker.Tests
{
    public class StrmResolutionAndGenerationTests
    {
        [Fact]
        public void ResolverAcceptsOneHttpTargetWithBomCrLfBlankLinesAndComments()
        {
            var wrapper = CreateWrapper("\r\n# generated by media manager\r\n  https://example.test/media?id=42\r\n", true);
            try
            {
                var result = StrmResolver.Resolve(wrapper, CancellationToken.None);

                Assert.True(result.IsSuccess);
                Assert.Equal("https://example.test/media?id=42", result.Source);
                Assert.Null(result.ErrorCategory);
            }
            finally
            {
                DeleteWrapper(wrapper);
            }
        }

        [Fact]
        public void ResolverLeavesDirectLocalPathsUnchangedWithoutReadingThem()
        {
            const string local = "/not-a-wrapper/episode.mkv";

            var result = StrmResolver.Resolve(local, CancellationToken.None);

            Assert.True(result.IsSuccess);
            Assert.Equal(local, result.Source);
        }

        [Fact]
        public void ResolverRejectsOversizedWrapperBeforeDecoding()
        {
            var wrapper = CreateWrapper(new string('x', StrmResolver.MaximumBytes + 1), false);
            try
            {
                var result = StrmResolver.Resolve(wrapper, CancellationToken.None);

                Assert.False(result.IsSuccess);
                Assert.Equal(StrmResolveError.TooLarge, result.ErrorCategory);
            }
            finally
            {
                DeleteWrapper(wrapper);
            }
        }

        [Fact]
        public void ResolverRejectsInvalidUtf8()
        {
            var wrapper = Path.Combine(Path.GetTempPath(), "theme-maker-test-" + Guid.NewGuid().ToString("N") + ".strm");
            File.WriteAllBytes(wrapper, new byte[] { 0xC3, 0x28 });
            try
            {
                var result = StrmResolver.Resolve(wrapper, CancellationToken.None);

                Assert.False(result.IsSuccess);
                Assert.Equal(StrmResolveError.InvalidEncoding, result.ErrorCategory);
            }
            finally
            {
                DeleteWrapper(wrapper);
            }
        }

        [Theory]
        [InlineData("https://example.test/one\nhttps://example.test/two\n", StrmResolveError.MultipleTargets)]
        [InlineData("file:///media/episode.mkv\n", StrmResolveError.UnsupportedScheme)]
        [InlineData("pipe:dangerous\n", StrmResolveError.UnsupportedScheme)]
        [InlineData("not a uri\n", StrmResolveError.InvalidTarget)]
        [InlineData("\n# only a comment\n", StrmResolveError.NoTarget)]
        public void ResolverRejectsAmbiguousUnsupportedOrMalformedWrappers(string contents, string expectedError)
        {
            var wrapper = CreateWrapper(contents, false);
            try
            {
                var result = StrmResolver.Resolve(wrapper, CancellationToken.None);

                Assert.False(result.IsSuccess);
                Assert.Equal(expectedError, result.ErrorCategory);
                Assert.DoesNotContain("example.test", result.ErrorCategory ?? string.Empty);
            }
            finally
            {
                DeleteWrapper(wrapper);
            }
        }

        [Fact]
        public void ResolverHonorsCancellationBeforeReadingAWrapper()
        {
            var wrapper = CreateWrapper("https://example.test/media\n", false);
            var cancellation = new CancellationTokenSource();
            cancellation.Cancel();
            try
            {
                Assert.Throws<OperationCanceledException>(() => StrmResolver.Resolve(wrapper, cancellation.Token));
            }
            finally
            {
                cancellation.Dispose();
                DeleteWrapper(wrapper);
            }
        }

        [Fact]
        public void RedactionRemovesTargetAndCredentialsFromErrors()
        {
            const string target = "https://user:secret@example.test/media?token=private#fragment";
            var redacted = StrmResolver.RedactForLog("ffmpeg could not open " + target, target);

            Assert.DoesNotContain(target, redacted);
            Assert.DoesNotContain("user", redacted);
            Assert.DoesNotContain("secret", redacted);
            Assert.DoesNotContain("example.test", redacted);
            Assert.Contains(StrmResolver.RedactedTarget, redacted);
        }

        [Fact]
        public void ResolutionPolicyAllowsResolverOnlyForGenerate()
        {
            Assert.False(ThemeGenerationPolicy.ShouldResolveStrm(false));
            Assert.True(ThemeGenerationPolicy.ShouldResolveStrm(true));
        }

        [Fact]
        public void DefaultsAndLimiterBoundSuccessfulNewSeriesButNotSkips()
        {
            var options = new ThemeMakerOptions();
            var limiter = new SuccessfulGenerationLimiter(1);

            Assert.Equal(1, options.Jobs);
            Assert.Equal(1, options.MaxNewThemesPerRun);
            Assert.True(limiter.CanGenerate);

            Assert.True(limiter.TryBeginUnit());
            Assert.False(limiter.TryBeginUnit());
            limiter.CompleteUnit(false);
            Assert.True(limiter.CanGenerate);

            Assert.True(limiter.TryBeginUnit());
            limiter.CompleteUnit(true);

            Assert.False(limiter.CanGenerate);
            Assert.Equal(1, limiter.SuccessfulGenerations);
        }

        private static string CreateWrapper(string contents, bool withBom)
        {
            var path = Path.Combine(Path.GetTempPath(), "theme-maker-test-" + Guid.NewGuid().ToString("N") + ".strm");
            File.WriteAllText(path, contents, new UTF8Encoding(withBom));
            return path;
        }

        private static void DeleteWrapper(string path)
        {
            try
            {
                File.Delete(path);
            }
            catch
            {
                // Test cleanup is best effort.
            }
        }
    }
}
